### ISSUE TITLE
REPL sharing title and image

### ISSUE THREAD

**Issue by rlaferla** [sveltejs/sites#100]
1.  The shared image for the REPL is too big.  This can be annoying on chat channels like Discord.
2.  The actual title of the REPL should be used when sharing instead of "Cybernetically enhanced web apps".

![repl](https://user-images.githubusercontent.com/1135694/70056704-e55daf80-15a9-11ea-8088-91ab34ee2c04.png)

**Comment by Rich-Harris** [comment]
closed via #223, thanks
