### ISSUE TITLE
Add search box to tutorials page

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sites#101]
**Is your feature request related to a problem? Please describe.**
Sometimes it's hard to find stuff

**Describe the solution you'd like**
A search bar: https://twitter.com/LucasHugdahl/status/1193747128486510592

Probably better to have a single universal search bar that shows results from docs, examples and tutorials (and blog posts?), appropriately labeled.

Have given no thought to how such a thing would be implemented.

**Comment by benmccann** [comment]
this is done
