### ISSUE TITLE
Public/sharable URL for repl list

### ISSUE THREAD

**Issue by andreasvirkus** [sveltejs/sites#102]
**Is your feature request related to a problem? Please describe.**
I'd wish to show my Svelte apps to friends or other people, maybe via a URL like `svelte.dev/apps/ba3f-6a424c662206`

**Describe the solution you'd like**
You could have a "Publish" button that generates a public URL for your REPL listing page (or it could be public by default with a hash in the url? 🤷‍♂ )

**Describe alternatives you've considered**
An alternative would be to git my solutions, bundle them myself and create a profile page... but the REPL is so convenient for small fiddles :3

**How important is this feature to you?**
Not that important. If you'd provide me some guidance, I'd love to work on this myself (as this also seems like a good "get your toes wet" issue?)

**Additional context**
I'm deeply in love with Svelte <3

**Comment by benmccann** [comment]
this exists on the new site
