### ISSUE TITLE
The repl download messes with encodings

### ISSUE THREAD

**Issue by burningTyger** [sveltejs/sites#103]
**Describe the bug**
Typing some umlauts such as `äöü` in the REPL's App.svelte and downloading it will mess up the umlauts to gibberish

**To Reproduce**
https://svelte.dev/repl/cefce44e52ee42a79123e6c23d108b54?version=3
Download, build and start to see the text

**Expected behavior**
`öäü` can be used and don't need to be fixed afterwards via encoding conversions

This looks correct:
![image](https://user-images.githubusercontent.com/263378/62230008-36be1e00-b3c1-11e9-9ed5-627f10c803ed.png)

This is what it really looks like when downloaded:
![image](https://user-images.githubusercontent.com/263378/62230060-4f2e3880-b3c1-11e9-97f7-b4c16ae159a0.png)

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
