### ISSUE TITLE
Non-responsive tables in API docs

### ISSUE THREAD

**Issue by xamgore** [sveltejs/sites#104]
Hi, seems that tables are not responsive for mobile clients, I can't scroll it on my phone with the latest chrome. svelte.dev/docs

<img src="https://user-images.githubusercontent.com/4586392/59150327-3a20d300-8a2a-11e9-8352-0a0802669c61.png" width=320>

I see two ways to solve it:

1. Wrap tables with `<div style="overflow-x: scroll">...</div>`
2. Chop table rows down.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
