### ISSUE TITLE
Adding a new component in homepage REPL widgets causes scroll jump

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sites#107]
Technically this issue probably belongs in the svelte-repl repo, but I'll forget about it if it's there

https://mobile.twitter.com/MohsenKhakbiz/status/1136676705110827008

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
