### ISSUE TITLE
examples sidebar-improvement

### ISSUE THREAD

**Issue by vedam** [sveltejs/sites#110]
**splitted this out from sveltejs/svelte#2641**

I would like to discuss an addition to examples-sidebar which would IMO eliminate the need to scroll endlessly downwards which is the current state. This is maybe a bit more future-proof too, if more examples are coming.
Not coded yet, just as a visual idea.

![svelte-docs-proposal](https://user-images.githubusercontent.com/64245/57025533-a6443600-6c37-11e9-86ff-08ae06c2f2cf.jpg)

**Comment by vedam** [comment]
Thumbs up on that, definitely an improvement in clarity IMO.
Maybe the active orange should be a tick lighter and the tags have to grow a bit on mobile (this can very easily look distracting), at least for my thumbs 😄

**Comment by dummdidumm** [comment]
Agree, if the side nav gets too big you'll have to scroll very long and not miss the category you are search for while doing it. With this it would mean you always know where to look, everything is in one place. This could be a nice addition to the docs section, too, if we start adding more doc pages.

**Comment by vedam** [comment]
OK, it looks like the Pill approach is having trouble with too many subcategories. That's why I thought about it again and searched for a more practicable possibility:
https://www.figma.com/file/d5OC7BNdcU32b0pArNLehe/svelte-sidebar-draft?node-id=0%3A1

**Comment by benmccann** [comment]
closing since the example page has been rewritten and no longer exists in its prior form
