### ISSUE TITLE
If the REPL can keep its content, it'd be great to send other people sample code

### ISSUE THREAD

**Issue by KennethKinLum** [sveltejs/sites#113]
Right now if I have some code sample on the Svelte REPL, I can send people some code samples:

https://svelte.dev/repl/64635232b5784bfa8997192ced12acd4?version=3.18.1

but if I forgot and a few days later come back and edited some code to experiment and saved it and didn't save a good version at the end, or just experimented with it and saved some bad code and then fork another version, now the version I sent to other people won't work any more.

Can it act somewhat like jsfiddle, so that a version of sample code, some URL like:

https://svelte.dev/repl/64635232b5784bfa8997192ced12acd4/12?version=3.18.1

(URL won't work, just a sample)  So that the 12 is the minor version?  So I can send to other people version 01 or 03, and I can keep on editing the code into version 4, 5, 6, 7 and it won't affect the version I sent to people?

Otherwise, I can in a few days, forgot that I sent to other people and edit that version. It'd fine if I fork another version and never touch that original version, but sometimes which URL is which might be forgotten and the original version is used and edited.

**Comment by benmccann** [comment]
closing since we now have hashes in the URL. please file an issue at https://github.com/sveltejs/svelte.dev/issues/new if more is needed
