### ISSUE TITLE
Spacing around code make doc harder to read

### ISSUE THREAD

**Issue by Arthur-Milchior** [sveltejs/sites#115]
### Describe the bug

The documentation is slightly hard to read, as there is a quite unusual spacing in the middle of English sentences.
![2021-10-19-141511_396x87_scrot](https://user-images.githubusercontent.com/357361/137907728-0eb06f36-e29f-4265-85bb-6bd0fb307ca0.png)

I suggest simply removing padding and marging in `.content.svelte-1itkhys code` of https://svelte.dev/_app/assets/vendor-123f37e5.css , which leads to the more standard
![2021-10-19-141459_413x86_scrot](https://user-images.githubusercontent.com/357361/137908091-c67aa522-7e2f-4997-b912-29a6fda36e1c.png)
This css field is also applied to code on the side of the window, but it does not seems to make a noticeable difference.

I suspect it originally comes from https://github.com/sveltejs/svelte/blob/master/site/src/routes/blog/%5Bslug%5D.svelte#L102

But my skills reach their limits here and I must admit that I don't know how to see what are all of the places where this css is used

### Reproduction

Open https://svelte.dev/docs#script 

Ideally on a bad quality screen where the difference of color around the code is almost invisible/where #eff8ff is almost undifferentiable from white

### System Info

```shell
chromium Version 94.0.4606.81 (Official Build) snap (64-bit)/firefox 93.0 (64-bit), ubuntu
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
Yeah, I have to say it looks very weird without the padding. The colours have recently been tweaked, the background should be visible even on low quality screens, so I'll close this — thanks
