### ISSUE TITLE
REPL module resolution doesn't respect "exports" entry in package.json.

### ISSUE THREAD

**Issue by hperrin** [sveltejs/sites#134]
The REPL's node module resolution doesn't respect the "exports" entry in packages' package.json files. This could mean that the REPL is running on an old version of node that didn't support this, but I don't know how to tell.

You can see this behavior here:
https://svelte.dev/repl/f9c535598baa4694b57f3d47dab4e58e?version=3.44.1

The error reads:
`Cannot find "/index.js" in @smui/textfield@6.0.0-beta.0`

The package.json for @smui/textfield@6.0.0-beta.0 includes this entry:

```json
  "exports": {
    "./package.json": "./package.json",
    ".": "./dist/index.js",
    "./character-counter": "./dist/character-counter/index.js",
    "./helper-text": "./dist/helper-text/index.js",
    "./icon": "./dist/icon/index.js"
  },
```

**Comment by Conduitry** [comment]
Luke has [a delightful library](https://github.com/lukeed/resolve.exports) that I would recommend trying to use for this.

**Comment by benmccann** [comment]
It looks like the resolution logic lives here if anyone wants to try integrating `resolve.exports`:

https://github.com/sveltejs/sites/blob/30d8f723fcaad76559cad7a450dd4b15ea05f462/packages/repl/src/lib/workers/bundler/index.js#L168

Or we could also try replacing the whole REPL with [sandpack](https://github.com/codesandbox/sandpack) or [web containers](https://webcontainers.io/) if anyone wants to do some benchmarking to see how they compare :smile:
