### ISSUE TITLE
Question to licensing on npm (MIT or LIL?)

### ISSUE THREAD

**Issue by oleuml** [sveltejs/sites#138]
Dear all,
I have one question about the license on npmjs. The README says MIT license and on the npm page the LIL is displayed. Which is the right one? The LISENCE file in the repo does not contain the MIT license, which is named and linked as MIT in the README.

Thanks in advance,
Ole

**Comment by Rich-Harris** [comment]
It's MIT — I've just opened #194 to add the relevant files, thanks
