### ISSUE TITLE
Some Features Request

### ISSUE THREAD

**Issue by shahul01** [sveltejs/sites#144]
Some of the features I thought to make Svelte REPL awesome.

// Socializing 
When reaching a repl from google etc it should show the original author and should show our name on it only after forking
Comment section for each repl -> can be used for others helping to solve, improve code.
Search others repl on svelte itself by title, username etc
Private repl
Follow users and see their(public) repl
use repl as iFrame
Archive or hide repl
Delete repl

// Others
Import downloaded archived code from repl (uploading zip)
Import github code to repl from url
Ability to hide or minimize warning or errors
Auto complete eg each block, importing component
CSS color picker on style block
Dark mode
The repl apps list has no prev page btn only next page btn...

Thanks!

**Comment by benmccann** [comment]
a lot of these have been implemented. some remain, but it's difficult to handle this with them all being in a single issue. probably better to file individual issues for the more important ones

**Comment by shahul01** [comment]
This shouldn't be marked as complete as  very few have been actually completed,

 in fact, an important option to download repl that was previously available has been removed in new version..

**Comment by benmccann** [comment]
Nonetheless this is no longer the repo for site-related issues, so all issues here have been closed. Please file an issue for the items that remain at sveltejs/svelte.dev
