### ISSUE TITLE
Autoscroll console

### ISSUE THREAD

**Issue by RamiAwar** [sveltejs/sites#148]
Seems weird that the console output does not automatically scroll down upon appending a new line. Is this intended behavior or can I work on a PR to add this feature?

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists

**Comment by benmccann** [comment]
I have a PR pending over at the new repo for a contributor's guide
