### ISSUE TITLE
<head></head> survives reloads

### ISSUE THREAD

**Issue by m59peacemaker** [sveltejs/sites#149]
I imported a module that injects its stylesheets into `<head>`, which persists across reloads, causing more style tags to be injected on each reload. I couldn't find any reliable way to hack around this. For example, trying to remove existing stylesheets before importing the module.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
