### ISSUE TITLE
Form submit breaks the REPL

### ISSUE THREAD

**Issue by guidobouman** [sveltejs/sites#153]
#### Issue
When a form accidentally submits, the REPL breaks without a warning.

#### Expected behaviour
A new build will trigger a refresh of the iframe.

#### Actual result
The iframe does not respond to new builds.

#### Repro link
https://svelte.dev/repl/6791e014cab94ccb837eea2fd41222a2?version=3.29.4

#### Suspected origin of the bug
https://github.com/sveltejs/svelte-repl/blob/master/src/Output/Viewer.svelte#L77-L80

In the iframe load event, when a navigation to another URL can be detected, the iframe could be rebuilt.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
