### ISSUE TITLE
Global immutable flag not working in REPL

### ISSUE THREAD

**Issue by axil** [sveltejs/sites#155]
When I turn on the immutable flag globally in the "compiler options" box in REPL it is not working (although it does when I build locally with rollup)

![image](https://user-images.githubusercontent.com/170910/89256068-81feb280-d64d-11ea-9a62-d8d16d575956.png)

I've copied the example project from step 16-g of the tutorial to the REPL
https://svelte.dev/repl/38ee1513be5e498397649956ea1a9e8a?version=3.24.0
and turned on the immutable flag globally instead of per-file setting as suggested in the tutorial. 
It works as if this flag was not set.

Interestingly though, the js code in the right "JS output" sidebar is changing the same way as when I set the immutable option
through the `<svelte:options immutable={true}/>` tag inside the component.

Chrome 83, Windows 7 x64

**Comment by benmccann** [comment]
I believe this flag was removed in svelte 5
