### ISSUE TITLE
[Proposal] Svelte Repl: use Skypack before falling back to Unpkg 

### ISSUE THREAD

**Issue by swyxio** [sveltejs/sites#160]
**Is your feature request related to a problem? Please describe.**
unpkg loads a ton of requests. this can cause issues due to 429 too many requests

example: https://svelte.dev/repl/7f9c4f7a0da0407cacd6c353a121b442?version=3.21.0

discord record of confusion: https://discordapp.com/channels/457912077277855764/457912077277855766/704383850922639460

**Describe the solution you'd like**
try using pika cdn - it compiles entire packages to a single file. probably faster.

**Describe alternatives you've considered**
do nothing

**How important is this feature to you?**
nice to have. hopefully as easy to implement as prefixing every package with "https://cdn.pika.dev"

@FredKSchott 's comments here https://twitter.com/FredKSchott/status/1254861844180692993

**Comment by benmccann** [comment]
looks like pika was renamed to skypack

going to go ahead and close this though as I believe PuruVJ did some investigation of similar alternatives like esm.sh and ran into issues around not being able to share the svelte runtime with it bundled. maybe we'll look ask jsdelivr though
