### ISSUE TITLE
Handlebars mode doesn't highlight single-bracket syntax

### ISSUE THREAD

**Issue by Osmose** [sveltejs/sites#161]
Hi! Thanks for the project! 

The REPL uses Handlebars syntax highlighting, which is workable, but I'm guessing was chosen before the switch to single brackets; double brackets gets highlighted, but single brackets does not.

It would be a nice improvement if we could somehow get the handlebars mode to accept single brackets as well, or otherwise make a Svelte-specific CodeMirror mode. I noticed this in the first place while reviewing a change to add Svelte highlighting to [Glitch](https://glitch.com/), where we also use CodeMirror and would probably be a consumer of a Svelte mode.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
