### ISSUE TITLE
Add code reformatting/indent to REPL

### ISSUE THREAD

**Issue by rlaferla** [sveltejs/sites#164]
PROBLEM:
I use the REPL frequently and perhaps my sveltejs/svelte-repl#1 complaint is that the indentation gets out of whack after a while and the code becomes unreadable.   I then have to copy the code to a local editor, reformat/indent it and then paste it back.

SOLUTION:
Add a button that reformats/reindents the code to prettify it.  

IDEAS:
Perhaps, the code in this post could be used as a starting point:

https://stackoverflow.com/questions/26360414/javascript-how-to-correct-indentation-in-html-string

**Comment by benmccann** [comment]
there's another issue in the https://github.com/sveltejs/svelte.dev/issues tracker for formatting, so closing this as a duplicate
