### ISSUE TITLE
Wanted to use and customize REPL - still a bit confused

### ISSUE THREAD

**Issue by 0gust1** [sveltejs/sites#165]
I wanted to use and extend the REPL with the purpose of integrating it in a backoffice application, allowing content contributors (familiar with HTML and a little JS) to edit and create content.

I did some reading in svelte.dev website code : [embed.svelte](https://github.com/sveltejs/svelte/blob/master/site/src/routes/repl/embed.svelte)
and [ReplWidget.svelte
](https://github.com/sveltejs/svelte/blob/master/site/src/components/Repl/ReplWidget.svelte)

to see how it's implemented, but I still struggle to get the "big picture" between the widget, the embed component, the REPL component itself and the webworkers.

If I achieve something, I'll be glad to contribute back some documentation.

**Comment by benmccann** [comment]
closing since the repl has been moved to https://github.com/sveltejs/svelte.dev and hopefully the last comment answered your question
