### ISSUE TITLE
Auto closing tags trigger on any greater than sign

### ISSUE THREAD

**Issue by trbrc** [sveltejs/sites#176]
It looks like the overall useful sveltejs/svelte-repl#14 / sveltejs/svelte-repl#17 is getting in the way in a few situations. Try for example to type out the following examples character by character:

```html
<button on:click={() => (counter++)}>Increment</button>
```

```html
<div class:too-much={counter > 10}>{counter}</div>
```

When you get to the greater than signs, you will end up with the following result:

```html
<button on:click={() =>
  │
</button>}
```

```html
<div class:too-much={counter >
  │
</div>}
```

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
