### ISSUE TITLE
The output pane does not receive touch events on mobile / tablet

### ISSUE THREAD

**Issue by mindrones** [sveltejs/sites#178]
See these issues:
• https://github.com/sveltejs/svelte/issues/2499
• https://github.com/sveltejs/svelte/issues/2550

I'm going to apply the fix described in https://github.com/sveltejs/svelte/issues/2550#issuecomment-487301991 while waiting to fix it here and publish it.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
