### ISSUE TITLE
Could the REPL show the component's state?

### ISSUE THREAD

**Issue by fvsch** [sveltejs/sites#179]
When doing the later steps of the tutorial, e.g. https://svelte.dev/tutorial/each-block-bindings, I find that I'm missing a way to inspect the current state of components.

I don't know if that would be possible, and a good fit for the REPL?

Tangential: it seems Svelte doesn't have an equivalent of the React and Vue DevTools extensions either.

PS: Svelte v3 is great, excited to use it. :100:

**Comment by benmccann** [comment]
we do have a svelte devtools now. there's an issue in https://github.com/sveltejs/svelte.dev/issues to consider integrating the REPL with it
