### ISSUE TITLE
Sitemap.xml

### ISSUE THREAD

**Issue by nosovk** [sveltejs/sites#18]
It would be nice to generate\update sitemap.xml with links to all content.

**Comment by benmccann** [comment]
What would be the point of this? There's only four pages on the site, so a web crawler will easily discover everything

**Comment by nosovk** [comment]
people use this repo as an example, small howto. In common people need to generate sitemaps, it's better to leave an example.

**Comment by benmccann** [comment]
Closing as duplicate of https://github.com/sveltejs/kit/issues/1142
