### ISSUE TITLE
REPL not saving - tries to PUT "undefined.json" and gets JSON.parse error

### ISSUE THREAD

**Issue by rmunn** [sveltejs/sites#189]
In https://github.com/sveltejs/kit/issues/3056, the issue reporter mentioned that he couldn't save to the REPL. I just tried, and I also couldn't save anything until I opened a new tab. In the new tab, saving sent a POST to `create.json` and it worked. But in the tab that failed, clicking the Save button sent a PUT request to `undefined.json`, which got a 500 response with payload `invalid input syntax for type uuid: "undefined"`. Which in turn caused a popup error message in the REPL saying "JSON.parse: unexpected character at line 1 column 1 of the JSON data".

The only difference I've found between the tab where I couldn't save and the tab where I could save is that in the original tab, I wasn't logged in. I clicked on the "Log in to save" link, got logged in, and then the Save button was doing a PUT to `undefined.json`. By copying my code into a new REPL tab, I was able to get a Save button that was doing a POST to `create.json` instead. So...

**Reproduction steps**

1. Open a new REPL tab
2. Log out if you were logged in
3. Edit the REPL title and code
4. Log in
5. Click Save button

That should cause a PUT to `undefined.json` instead of the POST to `create.json` that it's supposed to cause.

**Comment by Rich-Harris** [comment]
should be fixed by https://github.com/sveltejs/sites/pull/192
