### ISSUE TITLE
Importing external packages results in the REPL getting stuck bundling

### ISSUE THREAD

**Issue by kevmodrome** [sveltejs/sites#205]
This recently started to happen when you import an external package in the REPL. For example the following won't work:

```svelte
<script>
	import * as THREE from 'three';
</script>
```

Editing the REPL and removing the import does not fix the issue and you need to refresh the page.

**Comment by bluwy** [comment]
I wonder if this is related to #206 having CPU 100% for that

**Comment by Rich-Harris** [comment]
closed via #226
