### ISSUE TITLE
beforeUpdate/afterUpdate tutorial page use 100% CPU 

### ISSUE THREAD

**Issue by Gunyon** [sveltejs/sites#206]
### Describe the bug

[This page](https://svelte.dev/tutorial/update) use 100% of CPU

### Reproduction

Open https://svelte.dev/tutorial/update and see CPU load

### System Info

```shell
Ubuntu 20.04.3, Chrome, Firefox
```

### Severity

annoyance

**Comment by Rich-Harris** [comment]
closed via #226 — thanks
