### ISSUE TITLE
Edit this chapter links on svelte tutorial are broken

### ISSUE THREAD

**Issue by ZusorCode** [sveltejs/sites#212]
Looks like the variable isn't being set anymore

https://github.com/sveltejs/sites/blob/257ac05aea48bfb29ba61cc8205643de973e5e72/sites/svelte.dev/src/routes/tutorial/%5Bslug%5D/index.svelte#L76-L80

https://github.com/sveltejs/sites/blob/257ac05aea48bfb29ba61cc8205643de973e5e72/sites/svelte.dev/src/routes/tutorial/%5Bslug%5D/index.svelte#L157-L159

**Comment by Rich-Harris** [comment]
thanks!
