### ISSUE TITLE
add delete button to /repl

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sites#218]
Now that we have the ability to delete apps from `/apps`, it should be straightforward to add the ability to delete a single app from within `/repl` (albeit by requesting a `DELETE` from `/repl/[id]` rather than a `POST` to `apps/destroy`). Need to figure out what happens on the page after you've deleted though

**Comment by Conduitry** [comment]
> Need to figure out what happens on the page after you've deleted though

Bringing you to the /apps page seems like a straightforward and sensible thing to do after deleting the current REPL.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
