### ISSUE TITLE
404 Page at kit.svelte.dev missing CSS

### ISSUE THREAD

**Issue by omar2205** [sveltejs/sites#22]
404 page at kit.svelte.dev is missing 
```html
<link rel="stylesheet" href="/./_app/assets/start-ee31b6d0.css">
<link rel="stylesheet" href="/./_app/assets/Nav.svelte-ae76ea56.css">
```

**Describe the bug**
CSS is missing

**To Reproduce**
Visit https://kit.svelte.dev/whatever

**Comment by benmccann** [comment]
I think the missing CSS was fixed in https://github.com/sveltejs/kit/issues/920 though the 404 page design could stand to be updated
