### ISSUE TITLE
Consider using logical CSS properties.

### ISSUE THREAD

**Issue by Tropix126** [sveltejs/sites#228]
This change might be advantageous if you plan to support RTL languages with #207. Logical properties allow you to write dimensions for both LTR and RTL writing modes agonistically for the price of getting rid of the `top/left/bottom/right` terminology. At the time of writing this, they are supported in all major browsers. https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Logical_Properties

**Comment by Tropix126** [comment]
I can PR this if needed.

**Comment by Rich-Harris** [comment]
A PR would be great, thank you!
