### ISSUE TITLE
saved REPLs can't be recovered now

### ISSUE THREAD

**Issue by mvolkmann** [sveltejs/sites#235]
### Describe the bug

I think recent changes to the REPL have broken the ability to recover saved REPLs. I hope they aren't lost. I get this:

Yikes!
Encountered a 500 error
Please try reloading the page.

But reloading doesn't help.

I selected "Blocking all usage" for the severity below because this isn't related to upgrading the version of Svelte and it is much more than an "annoyance".

### Reproduction

I can't provide a REPL for this.

### System Info

```shell
This isn't related to what I have installed since the REPL is web-based.
```

### Severity

blocking all usage of svelte

**Comment by robertadamsonsmith** [comment]
I notice that the link on the 'Yikes!' page to the Discord chatroom, also causes the 'Yikes!' page to display (the two issues may be related):
https://svelte.dev/repl/chat

**Comment by oskarhane** [comment]
The link in the menu is wrong, you can manually go to https://svelte.dev/apps to get to them.
This is being addressed in an open PR: https://github.com/sveltejs/sites/pull/234.
