### ISSUE TITLE
Float: inline-start breaking REPL for everybody but Firefox users

### ISSUE THREAD

**Issue by SimoneGianni** [sveltejs/sites#240]
### Describe the bug

Currently REPL is broken, it displays the editor but not the results, using Chrome on OSX, and most probably every other browser except Firefox.

![image](https://user-images.githubusercontent.com/45396418/147125120-b5570e13-6e35-427c-863f-18ee215498c9.png)

After playing with it a bit, the problem seems to be that float: inline-start is used:

![image](https://user-images.githubusercontent.com/45396418/147125210-167f8105-b874-4346-951a-116c2281cba2.png)

This is unsupported by all browsers except Firefox, as reported in Mozilla developers reference: https://developer.mozilla.org/en-US/docs/Web/CSS/float?retiredLocale=it#browser_compatibility

So, I suppose this is happening to more or less everybody except those navigating with Mozilla, so putting it as high priority, cause users arriving to REPL to see what Svelte is all about are seeing a broken thing. 

Simply replacing it with a plain old float:left fixes the issue:

![image](https://user-images.githubusercontent.com/45396418/147125408-355b54f3-e13a-47ca-8e82-06a948c0cf3b.png)

### Reproduction

1. Use Chrome on OSX (it may happen with many other browsers too)
2. Open REPL page
3. Notice there is no "Hello world" display

### Severity

High, cause it's blocking REPL for working at all for most users.

**Comment by Tropix126** [comment]
Fixed by #239, awaiting merge.

**Comment by SimoneGianni** [comment]
Problem seems to be here https://github.com/sveltejs/sites/blob/master/packages/repl/src/lib/SplitPane.svelte#L117

**Comment by SimoneGianni** [comment]
@Tropix126 correct, looks like #239 fixes it, thanks.

**Comment by SimoneGianni** [comment]
Fixed in production.
