### ISSUE TITLE
Login to REPL fails with Github

### ISSUE THREAD

**Issue by BigBoulard** [sveltejs/sites#253]
Hi guys,

I can't login to REPL. When I click a popup shows up and close almost instantly. The app is not authorized yet in my Github Account but it's really a hindrance to code sharing.

Many thanks

**Comment by bluwy** [comment]
Do you have adblockers installed? Might want to try disabling them. Or maybe try logging in from an incognito tab.

**Comment by BigBoulard** [comment]
For whatever reason, now that I've restarted my computer, it's working now (adblock was disabled in the first place) :)

Thank you anyway

**Comment by cassepipe** [comment]
I actually experience the same problem in both latest firefox and chromium.
To get logged in, I have to refresh the page.
Same problem when deleting my apps. I have to refresh the page for them to actually disappear.
I have tried with adblocking off.
