### ISSUE TITLE
Donors logos are going over the viewport width on mobile

### ISSUE THREAD

**Issue by mcmxcdev** [sveltejs/sites#257]
![image](https://user-images.githubusercontent.com/16797721/147905434-2c218fac-4627-4034-ad4d-b417f37457d0.png)

**Comment by benmccann** [comment]
Weird. It looks fine on mobile to me. What OS and browser are you using?

**Comment by mhatvan** [comment]
This is with Brave Browser 1.33 on iPhone 11 with iOS 15.1.

You have to scroll down to the donors logo section and then attempt to swipe horizontally.

**Comment by geoffrich** [comment]
I can repro in Safari on iOS 15.2 (which makes sense, since it's all WebKit on iOS) ![image](https://user-images.githubusercontent.com/4992896/147956537-dd3a9fb3-8a86-4cab-8cca-92fa7148b6b3.png)

**Comment by lino-levan** [comment]
This looks resolved (iOS 15.4, iPhone SE Second Gen)?
![IMG_2548](https://user-images.githubusercontent.com/11367844/160453353-8c699af6-4455-4c0b-9d9b-97264614a139.jpg)

Did Apple fix a webkit bug or did someone do a pull request?

**Comment by mcmxcdev** [comment]
I cannot reproduce this anymore either, closing it.
