### ISSUE TITLE
Mapbox usage in tutorial/context-api is broken

### ISSUE THREAD

**Issue by jeroenheijmans** [sveltejs/sites#261]
The page at https://svelte.dev/tutorial/context-api is usable, but broken: it does not show any map at all in the rendered output.

Here's what I get on the initial load:

Console:

> VM767:845 Uncaught (in promise) ReferenceError: map is not defined
> VM767:513 GET https://api.mapbox.com/styles/v1/mapbox/streets-v9?access_token=undefined 401 (Unauthorized)
> VM765 about:srcdoc:164 Error: Unauthorized: you may have provided an invalid Mapbox access token. See https://www.mapbox.com/api-documentation/#access-tokens-and-token-scopes

Renders as:

![screenshot of tutorial page and errors, and no map](https://user-images.githubusercontent.com/1590536/147975298-54f4e8ad-2da9-4b76-a22b-0b03beae383e.png)

And after using the "Show me" button:

Console:

> VM768:519 GET https://api.mapbox.com/styles/v1/mapbox/streets-v9?access_token=undefined 401 
> VM765 about:srcdoc:164 Error: Unauthorized: you may have provided an invalid Mapbox access 

Screenshot:

![similarly broken page as screenshot before](https://user-images.githubusercontent.com/1590536/147975413-130c62df-6275-4c1d-a000-29853ceb996c.png)

I presume that it is supposed to work, using a Svelte Mapbox key? If we are supposed to enter our own key to show actual maps, that should be a bit clearer instead, I suggest.

**Comment by Conduitry** [comment]
It's supposed to be using Svelte's - you don't need to bring your own - but apparently that's broken or the build time var isn't correctly configured on our end.

**Comment by Conduitry** [comment]
Should be good now. Thanks for catching this!

**Comment by TheKinng96** [comment]
It is back now, but this time it is with another issue
![image](https://github.com/sveltejs/sites/assets/58755531/4b782f32-0155-4534-9b79-0cb653e6e1c0)
Cannot find "/[object Object]" in mapbox-gl@2.15.0
