### ISSUE TITLE
Bug - Browser find text flaky.

### ISSUE THREAD

**Issue by shahul01** [sveltejs/sites#265]
It shows no highlight on scrollbar, wrong number of found text and the found text disappears on scrollbar.
All these makes it impossible to search in REPL.

Browser - Chrome

Video: 
0:00-0:13 - Highlighted text isn't highlighted anymore after scroll. Found count is 1(Should be 2).
0:13-0:31 - I find again and this time count is 2 at start, after scrolling it is not highlighted anymore and count is 1.

https://user-images.githubusercontent.com/53307156/148678695-f17b832b-817b-4119-b4c1-02ddb3286b8a.mp4

**Comment by Conduitry** [comment]
This would be because of CodeMirror and isn't really something we can reasonably do anything about except completely rewriting the editor component or updating to CodeMirror 6 when that's ready and hoping that fixes it.

**Comment by shahul01** [comment]
ok got that

**Comment by benmccann** [comment]
closing since the site has been rewritten and now uses codemirror 6. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists

**Comment by shahul01** [comment]
yes, the new find bar solves the problem
