### ISSUE TITLE
Link icon missing on `kit.svelte.dev`

### ISSUE THREAD

**Issue by benmccann** [sveltejs/sites#271]
When you hover a heading it's supposed to show a link icon, but I'm getting a 404 fetching the icon

https://github.com/sveltejs/sites/tree/master/sites/svelte.dev/static/icons has `link.svg`
https://github.com/sveltejs/sites/tree/master/packages/site-kit/src/lib/icons has `link.svg`
https://github.com/sveltejs/sites/tree/master/sites/kit.svelte.dev/static/icons does not have `link.svg`

It's referenced and included three different ways: https://github.com/sveltejs/sites/search?q=link.svg

Is there anyway we can have a shared version of this or do we need to copy it into the SvelteKit project?

**Comment by Conduitry** [comment]
This got fixed at some point, and kit.svelte.dev isn't in this repo anymore anyway.
