### ISSUE TITLE
Svelte.dev example not working

### ISSUE THREAD

**Issue by ile** [sveltejs/sites#274]
### Describe the bug

Example here doesn't seem to work: https://svelte.dev/tutorial/writable-stores

### Reproduction

Try it at https://svelte.dev/tutorial/writable-stores

### Logs

```shell
index.d4c62bfd.js:60 running Svelte compiler version 3.46.2
index.d4c62bfd.js:60 Error: Could not load https://unpkg.com/svelte@3/internal/index.mjs (imported by ./App.svelte): 
    at R (/_app/assets/index.d4c62bfd.js:25:74383)
    at Js (/_app/assets/index.d4c62bfd.js:51:3334)
    at /_app/assets/index.d4c62bfd.js:51:20803
    at async /_app/assets/index.d4c62bfd.js:51:8739
    at async Ju.work (/_app/assets/index.d4c62bfd.js:51:2722)
```
```


### System Info

```shell
-
```

### Severity

annoyance

**Comment by bluwy** [comment]
I had experienced this before while working on the REPL locally. It doesn't happen very often, but I think it's because unpkg noticed repeated requests from the same client and throttled it. Not sure if we can do anything about it, except self-hosting ourselves.

**Comment by ile** [comment]
I tried to refresh it a few times: the error happened a couple of times. 90 % times it worked, 10 % not.

I lowered Brave's "shields", but it still happened from time to time.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
