### ISSUE TITLE
RSS feed navigation broken on Svelte Website

### ISSUE THREAD

**Issue by DhyeyMoliya** [sveltejs/sites#279]
While reading the [latest blog](https://svelte.dev/blog/accelerating-sveltes-development), I tried to open RSS feed link (https://svelte.dev/blog/rss.xml) given in the blog and found that it's not working.
Here's the error shown on the page :
![image](https://user-images.githubusercontent.com/6321840/150678992-51f485a1-0ae0-4d64-b55c-0af75f881510.jpeg)

**Comment by benmccann** [comment]
It works if you navigate directly to it. I guess we need to mark that link as `rel="external"` though I'm not sure how we'd do that since it's in an `.md` file. I'd just as soon remove it

**Comment by benmccann** [comment]
Actually, I think changing it from a relative URL to an absolute URL might fix it
