### ISSUE TITLE
Nav menu shows "Home" on all pages on mobile

### ISSUE THREAD

**Issue by bedewilson** [sveltejs/sites#28]
Another small issue that I noticed was that the Nav menu always shows "Home", rather than the name of the current page (when on mobile). Also there is no chevron to indicate that the link is actually a dropdown menu.

![recording(1)](https://user-images.githubusercontent.com/10662340/115862538-9d2d7e80-a477-11eb-872f-9f024f366e65.gif)

**Proposed Solution**
Adjust the Nav menu to replicate the behavior of the original Svelte site.

![recording(2)](https://user-images.githubusercontent.com/10662340/115863085-4f654600-a478-11eb-8a0c-56a54e7d4766.gif)

I'm happy to fix this also.

**Comment by benmccann** [comment]
Thanks! A fix would be great.
