### ISSUE TITLE
Pre-render option for svelte Repl?

### ISSUE THREAD

**Issue by whatnickcodes** [sveltejs/sites#280]
Would be nice to hit download and have HTML, JS, and CSS ready to go.

Anyone know if possible or point in right direction?

**Comment by Tropix126** [comment]
Is this proposing something like adding SSR support to REPL downloads, or just having the option to download static rendered contents in the REPL as HTML and CSS?

**Comment by whatnickcodes** [comment]
I am suggesting basically what `sapper export` does/did. SEO friendly, pre-rendered full page HTML+CSS+JS that can be uploaded straight to static service.

Possible? Currently the export HTML is blank.

**Comment by gtm-nayan** [comment]
Closing as duplicate of #169
