### ISSUE TITLE
[REPL] REPL does not download packages from github

### ISSUE THREAD

**Issue by vadimkorr** [sveltejs/sites#282]
If package.json conains something like

```
  "dependencies": {
    "some-lib": "github-user/some-lib#1.0.0"
  }
```

REPL says `Cannot find package some-lib@latest`

**Comment by Conduitry** [comment]
Is there a CORS-enabled, very heavily cached CDN for GitHub like unpkg is for npm? I doubt this would be feasible otherwise.

**Comment by longnguyen2004** [comment]
How about jsdelivr? Does it have CORS?

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
