### ISSUE TITLE
Kit website loads without CSS / sometimes doesn't load at all and fall to CF 502 Error page.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/sites#285]
![Snímka obrazovky z 2022-01-28 15-53-47](https://user-images.githubusercontent.com/34808350/151570840-a5be7e1e-dc12-4a54-abf0-672346655f78.png)
![Snímka obrazovky z 2022-01-28 16-16-24](https://user-images.githubusercontent.com/34808350/151572321-d790719c-157b-4396-8fcc-17a7b52c78db.png)

**Comment by b-fuze** [comment]
I'm also experiencing this as well

**Comment by geoffrich** [comment]
Thanks for the report. Currently investigating.

**Comment by ignatiusmb** [comment]
We're back!
