### ISSUE TITLE
Feature request: Enable to embed REPL using embed.ly

### ISSUE THREAD

**Issue by shinokada** [sveltejs/sites#286]
Gist, Codepen, and others are enabled to embed codes by inserting a URL.
Is it possible to do the same with Svelte REPL?

**Comment by Tropix126** [comment]
Embedding REPLs has been discussed a few times before I believe (#93, #4866) and the general consensus seems to be that it would cause issues regarding bandwidth limitations.

**Comment by bluwy** [comment]
Looks like this duplicates #93. Closing in favor of that.
