### ISSUE TITLE
[REPL] Splitter does not properly move with pointer on Firefox

### ISSUE THREAD

**Issue by andirady** [sveltejs/sites#288]
The pane splitter in the REPL page doesn't follow the cursor on Firefox.
The splitter somehow moved to the left of the screen before following the cursor.

**Comment by bluwy** [comment]
Reproducible in macos m1, firefox 96.0.3

https://user-images.githubusercontent.com/34116392/151751050-24f00c61-64df-47ef-a7e1-fab9ad515e23.mov

**Comment by brunnerh** [comment]
Can also happen in Chrome (v.97.0.4692.99, Win 10, 64bit)

**Comment by Mlocik97** [comment]
can reproduce in firefox, but in chrome it works fine for me.

**Comment by geoffrich** [comment]
I can reproduce on Firefox, but noticed something interesting: once I resize the screen, the splitter moves with the cursor.

**Comment by andirady** [comment]
As @geoffrich mentioned, the splitter behaves correctly after the window was resized.
I ran some debugging and found out that the ``size`` at startup is somehow twice the actual size.
For example, the actual div with is 2560px, but at start up, ``size`` is 5120px as shown in screenshot below:

![image](https://user-images.githubusercontent.com/385785/153720543-14debc3d-537b-4857-af62-899089b93aef.png)

This is something to do with ``bind:clientWidth``. It could be that the bug is at svelte, not on the ``SplitPane.svelte``. 🤔

**Comment by andirady** [comment]
I did some debugging, it seems that at startup, the ``width`` field in ``index.svelte`` is 0. This causes the ``mobile`` field to be set, hence setting the ``$toggleable`` to ``true``. Which enables the ``.toggleable`` class hence the ``size`` in ``SplitPane.svelte`` is computed to be twice the size of the screen.
The ``$toggleable`` immediately turns ``false`` but the ``size`` in ``SplitPane.svelte`` doesn't change, probably since it's already mounted.

**Comment by bluwy** [comment]
Fixed in #359
