### ISSUE TITLE
[REPL] It throws error from old code, that was already rewritten in REPL.

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/sites#294]
Hello,

when I create some REPL, I start typing code, in console I get error "nam is not defined" in moment when in code there is "name" (was name like few seconds before), then I wait, clear console, change just space or add new line to code, but it again throw that error, even when in code there is "name", while it feels like compiled code still contains "nam" as name of variable, function or something.

https://youtu.be/W4-ljUtKM_A

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
