### ISSUE TITLE
[Kit] bad contrast in code examples in FAQ

### ISSUE THREAD

**Issue by Mlocik97** [sveltejs/sites#295]
![Snímka obrazovky z 2022-02-07 19-48-00](https://user-images.githubusercontent.com/34808350/152852186-17ef2997-d751-4604-8bd1-76944bd3139b.png)

**Comment by PuruVJ** [comment]
Hi, can you post screenshot of what you're seeing? I'm unable to see any problems on my end

**Comment by henrikvilhelmberglund** [comment]
https://svelte.dev/faq looks like this for me
![sveltedevfaq](https://github.com/sveltejs/sites/assets/110549389/c9c8dca9-3535-4a8e-8b2a-75a5a603a6bc)
Text contrast ratio is about 2.

**Comment by PuruVJ** [comment]
Oh!! Gotcha!

We're working on a new version of the site, where it's fixed and looks like this. The site should be released soon, so we probably won't be fixing the current version's code snippets.

<img width="768" alt="CleanShot 2023-05-19 at 11 39 43@2x" src="https://github.com/sveltejs/sites/assets/47742487/ab133e5d-edab-46c8-9248-87a3330c3d56">
