### ISSUE TITLE
REPL: Disable auto-close (brackets & tags), either globally or as a user setting

### ISSUE THREAD

**Issue by rgossiaux** [sveltejs/sites#307]
These drive me absolutely insane, they're not what I intend a significant portion of the time (eg if I go to surround some existing code with a new tag, I'll write the open tag before the block and then have to delete the close tag that gets generated) and in some cases they are completely wrong (#176).

Personally I am in favor of removing these entirely, but I wanted to file this issue first to get some feedback & see what other folks who use the REPL think. If some people like having these on, maybe making them as a user setting would be better.

Here's the code reference where these are configured: https://github.com/sveltejs/sites/blob/280c63631a329c53445c1f5f59d1515e52fac3d0/packages/repl/src/lib/CodeMirror.svelte#L171

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
