### ISSUE TITLE
The new banner is intrusive

### ISSUE THREAD

**Issue by sharu725** [sveltejs/sites#310]
Please keep the banner in the homepage. It is on docs, blogs, even on REPL, tutorial.

**Comment by pngwn** [comment]
It is meant to be noticeable across the site. It doesn't block any functionality, we have taken great care to ensure that. 

If the banner is blocking specific functionality then please let us know.

**Comment by baryphonic** [comment]
Please add an option to close or at least hide the banner in the REPL, ideally with the ability to remember user preferences. On a phone, the banner is excessively obtrusive. This may seem like an odd use case, but I find the REPL quite helpful for validating components on mobile before putting them into my code, and, besides, the REPL was clearly designed to be responsive.

With the banner up, the REPL is unusable in landscape mode, and is still a major UX hassle in portrait mode.
