### ISSUE TITLE
REPL UX with Political Banner on Mobile

### ISSUE THREAD

**Issue by baryphonic** [sveltejs/sites#319]
On a phone, the pro-Ukraine banner in the REPL is excessively obtrusive. This may seem like an odd use case, but I find the REPL quite helpful for validating components on mobile before putting them into my code, and, besides, the REPL was clearly designed to be responsive.

With the banner up, the REPL is unusable in landscape mode, and is still a significant UX hassle in portrait mode.

Please add an option to close or at least hide the Ukraine banner in the REPL, ideally with the ability to remember my preferences.

**Comment by jeremybradbury** [comment]
agreed. i use it on mobile too, not just for testing, but development.

I appreciate the support, but a close/hide button would be really nice... even if it comes back on refresh or expires after 24 hours etc.

**Comment by benmccann** [comment]
the banner has been removed and the current banner component that may be used for future banners has an ability to close it
