### ISSUE TITLE
Documentation for stack integration

### ISSUE THREAD

**Issue by IRod22** [sveltejs/sites#331]
Does Svelte plan on including docs for how to integrate Svelte into a stack? For example, how could a complex app manage state without creating many stories? What about testing an application?
These may need to be discussed with the core team as the framework matures

**Comment by bluwy** [comment]
I believe they are covered at https://sveltesociety.dev/recipes

**Comment by benmccann** [comment]
Also, things like testing an application will be covered by SvelteKit. E.g. when you create a new SvelteKit application it asks you if you'd like to setup Playwright. And there's also a Svelte FAQ about it as well: https://svelte.dev/faq#how-do-i-test-svelte-apps

I'm going to close this given the existing solutions that are in place
