### ISSUE TITLE
Documentation is displayed incorrectly in a mobile browser.

### ISSUE THREAD

**Issue by mrnektom** [sveltejs/sites#332]
![Screenshot_2022-05-04-12-42-34-994_com brave browser](https://user-images.githubusercontent.com/40566268/166659114-fb19c220-db3d-43ed-9db4-09550de7c63c.jpg)

**Comment by MrNektom** [comment]
Need to limit the size of the table and add horizontal scrolling to it

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
