### ISSUE TITLE
[REPL question] Compiling Svelte code in the browser

### ISSUE THREAD

**Issue by cofob** [sveltejs/sites#334]
Hello! I want to make a page builder that compiles svelte on the client side and sends it to the server (something like [scratch](https://scratch.mit.edu/)). The difficulty is that I need to somehow specify additional svelte files that are needed for compilation. The server doesn't have node.js installed.

For example the client wants to compile:
```svelte
// typescript support is optional
<script lang="ts">
    import WidgetCard from "ui/WidgetCard.svelte";
</script>

<WidgetCard/>
```

`ui/WidgetCard.svelte` content:
```svelte
<script lang="ts">
  // code can have external dependencies
  import axios from 'axios';
</script>

<div>
  <p>Example widget</p>
</div>
```

And get the output code that are generated by `npm run build`.

But you can't specify additional files like ``WidgetCard.svelte`` in the `svelte.compile` method, so the compile won't produce valid code. In REPL you somehow solved this problem, but after a quick look at the source code I still don't understand how you did it. Sending the source code of the widgets to the client is not a problem. Thank you in advance for your help.

**Comment by bluwy** [comment]
The svelte compiler compiles on a per-file basis. For multiple files, you'd want to bundle them up which involves using a bundler. The Svelte REPL uses Rollup as the bundler, in fact the Svelte compilation is [done via Rollup plugin](https://github.com/sveltejs/sites/blob/5417177ec85af6211302e9f06d69bb9cd8a499bd/packages/repl/src/lib/workers/bundler/index.js#L118) too. Check out https://github.com/sveltejs/sites/tree/master/packages/repl/src/lib/workers/bundler for inspiration. Closing as this is more of a discussion, but you can continue on the discussion or bring it to discord.
