### ISSUE TITLE
REPL: Error: Unexpected token (Note that you need plugins to import files that are not JavaScript)

### ISSUE THREAD

**Issue by ZerdoX-x** [sveltejs/sites#335]
https://svelte.dev/repl/2038d78fb2f24ea28db80550f220fc0f?version=3.48.0

Trying to use `@splidejs/svelte-splide` in repl. But repl seems can't proccess this file: https://unpkg.com/@splidejs/svelte-splide@0.2.1/utils/isObject/isObject.js

![image](https://user-images.githubusercontent.com/49815452/167563410-8a81ae47-b4a8-4747-a23e-3477abcbccff.png)

**Comment by ZerdoX-x** [comment]
I got different errors in different browsers. This is how chromium reacts: 
![image](https://user-images.githubusercontent.com/49815452/167563849-49af840e-6c3e-4d49-b04f-408c09849fee.png)

**Comment by ZerdoX-x** [comment]
Also when editing this REPL i couldn't save it:

can't access property "imports", o is null
![image](https://user-images.githubusercontent.com/49815452/167566640-77aa4e72-a9f3-4daf-b41e-a04b82c833d7.png)

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
