### ISSUE TITLE
REPL: Events defined with addEventListener() are not undefined after quick update, thus making them duplicate

### ISSUE THREAD

**Issue by thonkinator** [sveltejs/sites#341]
To reproduce this, create an event listener with addEventListener() (any event, like a keypress) and make it console.log the number 1. This works fine. However, change the 1 to a 2, causing a reload, and now 1 and 2 will be logged when the event is fired. This means that the events are not being undefined, which could cause unwanted bugs in the REPL.

**Comment by bluwy** [comment]
Similar #146

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
