### ISSUE TITLE
[docs] Svelte tutorial is not searchable

### ISSUE THREAD

**Issue by shanehh** [sveltejs/sites#343]
### Describe the bug

Hi teams

`ctrl/command + f` or just `type` not works for `select/options` at https://svelte.dev/tutorial/

It's not a short list. I feel it's hard to find a specific section.

![image](https://user-images.githubusercontent.com/49306726/164603102-3086c420-0ebe-48d5-bb76-21dfed3adee7.png)

Can team think about make `select/options` a plain list, like Go or just like https://svelte.dev/docs

https://go.dev/tour/welcome/1

![image](https://user-images.githubusercontent.com/49306726/164603332-57be8242-afcd-4b92-b1cb-eba7eb0798f4.png)

### Reproduction

see https://svelte.dev/tutorial/

### System Info

```shell
Browsers:
    Chrome: 100.0.4896.127
    Safari: 14.1.2
```

### Severity

annoyance

**Comment by benmccann** [comment]
it is now searchable
