### ISSUE TITLE
Font does not make for a good reading experience

### ISSUE THREAD

**Issue by finkrer** [sveltejs/sites#347]
## The problem

The main font used for the documentation is Overpass Light (`font-weight: 300`). This is in contrast to most other websites that use `font-weight: 400`.

Light fonts don't help readability, as indicated by [research](https://www.researchgate.net/publication/309593009_Legibility_of_Light_and_Ultra-Light_Fonts_Eyetracking_Study).

Now, I understand that this weight might have been chosen because of [the way macOS renders fonts](https://news.ycombinator.com/item?id=23553486). However, this is not the case for other OSes, and people who disabled font smoothing on macOS. As a result, the body text is just too light and not very legible, just compare Svelte's and React's homepage.

### Svelte:
<img width="559" alt="image" src="https://user-images.githubusercontent.com/22712590/170865662-efe8ca86-9983-49df-8019-36bc6d605618.png"></div>
### React:
<img width="374" alt="image" src="https://user-images.githubusercontent.com/22712590/170865674-15815036-69d6-404f-bae9-1aeb54cc61ff.png"></div>

This is even more noticeable on colorful backgrounds:

<img width="659" alt="image" src="https://user-images.githubusercontent.com/22712590/170865794-8eac28b6-ad3f-4976-8831-5ee514929551.png">

These elements are not very readable, and, in fact, break the WCAG contrast guidelines.

## Possible solutions

I think it's necessary to at least use the normal Overpass font with `font-weight: 400`.

**Comment by benmccann** [comment]
> I think it's necessary to at least use the normal Overpass font with font-weight: 400.

I don't notice any difference until I set `font-weight: 600`

**Comment by finkrer** [comment]
Hi Ben, thanks for replying.

This is because only weights 300 and 600 are defined in CSS, as you can see here.
https://github.com/sveltejs/sites/blob/828d5284dc7ae651ebe496b15adcca8876efe69d/packages/site-kit/src/lib/base.css#L74-L91

In fact, the site is _already_ set to `font-weight: 400`.
https://github.com/sveltejs/sites/blob/828d5284dc7ae651ebe496b15adcca8876efe69d/packages/site-kit/src/lib/base.css#L143-L150

It's just that weight 400 isn't defiined, and so the browser defaults to the closest one.

Essentially, the fix would be adding the following CSS:
```css
/* overpass-400normal - latin */
@font-face {
	font-family: 'Overpass';
	font-style: normal;
	font-weight: 400;
	src: local('Overpass Regular '), local('Overpass-Regular'),
		url('./fonts/overpass/overpass-latin-400.woff2') format('woff2');
}
```
Even the font file is already there.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists

**Comment by finkrer** [comment]
Yeah, not really applicable now. The readability of EB Garamond is questionable, but at least that's how it's supposed to look. Still, kinda sad that this hadn't been addressed before the rewrite.
