### ISSUE TITLE
Prevent svelte repl from being overwritten

### ISSUE THREAD

**Issue by Explosion-Scratch** [sveltejs/sites#348]
One of my projects was totally ruined because someone edited it after I sent them a link without me realizing that other people can just edit your repls. Here is my proposed solution:

1. User makes a repl and saves it
2. User sends/shares the link
3. User B makes changes to the repl
  a. These changes are reflected locally but not saved to the original repl.
  b. There is a prompt after a few minutes of editing to fork and save
4. Done, happy users

**Comment by Prinzhorn** [comment]
> without me realizing that other people can just edit your repls

I don't think they can, that would be horrible.

https://github.com/sveltejs/sites/blob/70a2f338b5f49af4acf130a3127dda826175772b/sites/svelte.dev/src/routes/(authed)/repl/%5Bid%5D/AppControls.svelte#L29

https://github.com/sveltejs/sites/blob/70a2f338b5f49af4acf130a3127dda826175772b/sites/svelte.dev/src/routes/(authed)/repl/%5Bid%5D/AppControls.svelte#L97-L100

**Comment by Prinzhorn** [comment]
Out of curiosity I dug a little deeper and it seems even down to the db level this should not be possible, the gist needs to belong to the current user https://github.com/sveltejs/sites/blob/06f0de39ac789617dcfa9b3f45261aafc507ff64/db/setup.sql#L143

**Comment by Explosion-Scratch** [comment]
Yeah, sorry for not closing this earlier, this doesn't actually happen (anymore?) I saw a post on Reddit about it (can't find it anymore), and tested it. That repl seemed to save edits by anyone.
