### ISSUE TITLE
Include --template svelte-ts on the getting started homepage

### ISSUE THREAD

**Issue by Jojoshua** [sveltejs/sites#356]
I noticed that the recommended getting started page is not using degit anymore and changed to 

npm init vite my-app -- [--template svelte](https://github.com/vitejs/vite/tree/main/packages/create-vite/template-svelte) 

This is fine but I had to go hunting github/google for the right way to initialize using Typescript and eventually I found **npm init vite my-app -- --template svelte-ts** is what I was needing. Please consider the Typescript projects and make this easier to find.

**Comment by gtm-nayan** [comment]
The recommended way to initialize Svelte projects has been changed to SvelteKit. If doing it through vite, the docs recommend `npm init vite` now which will make both templates discoverable.
