### ISSUE TITLE
REPL: process is not defined

### ISSUE THREAD

**Issue by bayre** [sveltejs/sites#360]
This issue appears to have crept back in https://github.com/sveltejs/svelte-repl/issues/105

Here is a minimal reproduction based on Tan's screenshot https://svelte.dev/repl/2c3f456eae7244399c24963d0195a5fb?version=3.49.0

**Comment by jangxyz** [comment]
Came upon this error as well. I was trying the [@tanstack/table](https://tanstack.com/table/v8) library for svelte.

For a quick fix, inserting a fake process object at the front did work.

```javascript
globalThis.process = { env: { NODE_ENV: 'production' }};
```

<details>
<summary>Screenshot</summary>

<img width="1069" alt="image" src="https://user-images.githubusercontent.com/52015/218063033-86e83fea-3bdc-489d-a3ed-adec681e994d.png">

</details>

**Comment by benmccann** [comment]
`process` is only available in the Node global namespace and not in the browser global namespace. Offending packages should be fixed
