### ISSUE TITLE
REPL login fails with 500 - auth is broken in production

### ISSUE THREAD

**Issue by jeremybradbury** [sveltejs/sites#366]
I was just trying to access some saved examples on my user page... but there are probably others not able to save things.

https://svelte.dev/auth/login

<img width="1067" alt="Screen Shot 2022-08-11 at 12 38 58 PM" src="https://user-images.githubusercontent.com/1664387/184225305-53eec0e5-dd70-459b-bdf9-08ade993b1f4.png">

**Comment by benmccann** [comment]
fixed. thanks for the report
