### ISSUE TITLE
REPL: Problems with text input on mobile with tab characters

### ISSUE THREAD

**Issue by FeldrinH** [sveltejs/sites#369]
Editing code in the REPL on a mobile device seems to be broken around horizontal tab characters.

Specifically, when trying to add a character immediately after or before a tab or delete the tab itself the edit shows briefly and is then immediately reverted.

This happens consistently on my Samsung Galaxy S10e and Sony Xperia XZ Compact, both running the default Chrome browser on Android.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
