### ISSUE TITLE
[BUG] Link to SvelteJS FAQ, in SvelteJS FAQ

### ISSUE THREAD

**Issue by lukaszpolowczyk** [sveltejs/sites#373]
This file
https://github.com/sveltejs/sites/blob/master/sites/svelte.dev/src/routes/faq/index.svelte

Includes 

```svelte
See also the <a href="https://svelte.dev/faq" rel="external">Svelte FAQ</a> for questions relating
		to Svelte directly.
```

It is not a problem in `https://kit.svelte.dev/faq`.
But in `https://svelte.dev/faq`, it is pointless.

Link to SvelteJS FAQ, in SvelteJS FAQ.

I don't know if this needs to be replaced or removed....

**Comment by benmccann** [comment]
yeah, it should be removed. though I don't particularly want to make any changes until https://github.com/sveltejs/sites/pull/371 is merged
