### ISSUE TITLE
REPL package  EUNSUPPORTEDPROTOCOL 

### ISSUE THREAD

**Issue by carlskii** [sveltejs/sites#380]
Hi,

Thanks for the amazing work in everything your team is doing. 

I'm trying to build my own REPL, but when I clone this repo and try to use the `sites/packages/repl` I get an `EUNSUPPORTEDPROTOCOL` error when I `npm install'

```
$npm install
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

All my other Svelte projects work perfectly fine.

**Comment by Conduitry** [comment]
`workspace:*` appears in https://github.com/sveltejs/sites/blob/master/packages/repl/package.json and is pnpm syntax https://pnpm.io/workspaces#workspace-protocol-workspace - If you're not using pnpm or if you're not using the package as part of a monorepo, this will need to be adjusted.
