### ISSUE TITLE
README.md on sites isn't novice friendly with git clone

### ISSUE THREAD

**Issue by RocketDerp** [sveltejs/sites#381]
README.md could be changed to

    git clone https://github.com/sveltejs/sites.git

So that authentication problems don't exist for users following the instruction. Currently it has git@ username

**Comment by benmccann** [comment]
I guess you're talking about https://github.com/sveltejs/sites/tree/master/sites/hn.svelte.dev ?

But it just says `git clone git@github.com:sveltejs/sites`, which I expect to work and doesn't include a username. Can you share what command you ran and the error you got?

**Comment by RocketDerp** [comment]
As the instructions stand now, you get:

Cloning into 'sites'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

**Comment by benmccann** [comment]
Hmm, I guess you don't have a key setup for your account: https://docs.github.com/en/authentication/troubleshooting-ssh/error-permission-denied-publickey

Ok, I've updated the instructions
