### ISSUE TITLE
REPL builder crashes on infinite loops

### ISSUE THREAD

**Issue by brandonmcconnell** [sveltejs/sites#382]
## Describe the bug

The REPL builder crashes on infinite loops rather than reporting them via an error and allowing the dev to modify/save the REPL to resolve the bug.

Oftentimes, if this happens in a REPL I'm working on, I have to continuously reload the page, quickly switch tabs, and copy the source to a local editor to resolve the bug, only to then paste the code back into a fresh REPL, as the infinite looping one is endlessly stuck.

## Reproduction

I've created one such example that shouldn't crash immediately (on larger screens at least). However, if you shrink the viewport size of the REPL preview to where the text gets truncated, you'll see it freezes completely.

**REPL:** https://svelte.dev/repl/deaa7c99b06f4ecf8921174a88b33538?version=3.50.1

## System Info

_Unnecessary — not local issue_

## Severity

annoyance

**Comment by Conduitry** [comment]
Transferred. But I agree that this feature request certainly sounds halting-problem-y.

**Comment by brandonmcconnell** [comment]
@Prinzhorn Yeah, if there's some trickery we can do here to detect and prevent that, that'd be great.

I also agree— I think a way to set a REPL to be able to be saved first before running would be ideal, maybe as an option disabled by default.

**Comment by brandonmcconnell** [comment]
Btw @Prinzhorn, here is another example that demonstrates the same issue, and I don't quite understand where the recursive issue would be coming from:
https://svelte.dev/repl/fa3352f06f004df4b0028f4fc654c8c0?version=3.50.1
☝🏼 un-comment the `{(() => i++)()}`

Here is the source, with that line pre-un-commented:
```svelte
<!-- App.svelte -->

<script>
	let arr = [1, 2, 3];
	let i = 0;
</script>

{#each arr as elem}
	{(() => i++)()}
{/each}
```
☝🏼 this will break

What is it about running `{(() => i++)()}` within the template that causes such a break?

**Comment by brandonmcconnell** [comment]
& related but without causing the loop issue— why, when I move the `i++` logic into the script logic does it computed before the loop so all iterations have the same value:
https://svelte.dev/repl/a9c8110a13bb4ff88960850b96b2e2a4?version=3.50.1

Source:
```svelte
<!-- App.svelte -->

<script>
	let arr = [1, 2, 3];
	let i = 0;
	let skip = (num = 1) => {
		i += num;
		return '';
	};
</script>

{#each arr as elem}
	{skip()}
	{i}
{/each}
```

**Comment by Prinzhorn** [comment]
Your last two examples are not directly related to this issue here. There are issues in Svelte about this already (https://github.com/sveltejs/svelte/issues/7295#issuecomment-1046235644) and I personally think that your examples should straight up not compile in Svelte 4. I think at least some of the Svelte team was in the same boat as me on that. Mutating state from inside the template is undefined behavior and doesn't make sense. If you call a function it needs to be pure, e.g. sth. like `formatDate(date)`. It should not have any side effects whatsoever.

**Comment by benmccann** [comment]
closing since the site has been rewritten and I'm not sure if this is still an issue in svelte 5. please file at https://github.com/sveltejs/svelte.dev/issues/new if an issue persists
