### ISSUE TITLE
Footer bar in REPL throws console error on hover

### ISSUE THREAD

**Issue by saibotsivad** [sveltejs/sites#383]
**What I did:**

Open a REPL in Firefox `105.0.2 (64-bit)` on macOS `12.4`, then open the dev console, then hover my mouse over the footer promo.

**What happened:**

On (every? most? there's probably throttling going on) mouseover events, I get a thrown console error:

```
Error: Attempted to prefetch a URL that does not belong to this app
```

<img width="1023" alt="image" src="https://user-images.githubusercontent.com/91254/194618530-6b2802fb-d073-4803-a4d4-f5e470eaa02e.png">

**What I expect to happen:**

The error should not be thrown.

**Comment by saibotsivad** [comment]
Actually, it looks like this is related to https://github.com/sveltejs/kit/issues/6463 which was addressed here https://github.com/sveltejs/kit/pull/6518 but the issue doesn't seem to be addressed entirely since I would expect this error to not be thrown (at most a `console.warning`).

From the [SvelteKit docs](https://kit.svelte.dev/docs/link-options#disabling-options) it looks like we could just add the `data-sveltekit-prefetch="off"` on some parent node, at least for now.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
