### ISSUE TITLE
svelte.dev/chat redirects to invite pointing to archived channel on Discord

### ISSUE THREAD

**Issue by ItsAleph** [sveltejs/sites#389]
Current invite [here](https://github.com/sveltejs/sites/blob/master/sites/svelte.dev/src/routes/chat/%2Bserver.js) points to the #svelte-archive channel on Discord, which is (as suggested from it's name) archived and replaced by the #community-chat channel (as far as i see). My suggestion is to generate a new invite which will point to A. the #rules channel or B. to the #community-chat channel. Here's invite i created pointing to the #community-chat channel (though of course you can create your own): https://discord.gg/MzsWBFWspp
It's settings are as following:
- Invite Channel: #community-chat
- Expire After: Never
- Max Uses: Infinite
- Temporary Membership: Disabled (because that's how the current link works)

**Comment by bluwy** [comment]
Ah that might be the reason why many ask for support in `#community-chat` without reading the rules. Pointing to `#rules` make sense. Maybe we could use https://discord.gg/svelte instead too?

**Comment by Conduitry** [comment]
Having https://svelte.dev/chat redirect to https://discord.gg/svelte rather than Rich's personal invite link makes sense to me.

**Comment by benmccann** [comment]
fixed: https://github.com/sveltejs/sites/commit/58b7125ea307beddd8f98be4318e79d7919711a0
