### ISSUE TITLE
Navbar links require double click on landscape touch devices

### ISSUE THREAD

**Issue by bedewilson** [sveltejs/sites#39]
Currently when in the desktop layout (i.e. not the dropdown menu) on touch devices, links have to be touched twice to navigate.

The `<Nav>` component has the following code to intercept touch events and open the responsive menu.
```javascript
function intercept_touchstart(event) {
  if (!open) {
    event.preventDefault();
    event.stopPropagation();
    open = true;
  }
}
```
The problem is that this function runs on both mobile and desktop layouts. So for touch devices showing the desktop layout, the first touch toggles the `open` variable (which has no visible effect), and the second touch is passed through to the link which then navigates.

**Comment by Rich-Harris** [comment]
closing per https://github.com/sveltejs/sites/pull/40#issuecomment-996381071
