### ISSUE TITLE
Repl not loading svelte compiler

### ISSUE THREAD

**Issue by iluvsoup** [sveltejs/sites#394]
# Description
The [repl](https://svelte.dev/repl) is not loading the svelte compiler

![image](https://user-images.githubusercontent.com/94307595/201038657-e0e690d6-aaaa-44eb-a538-90839c37b4e3.png)
(This message never goes away)

I suspected this might be an issue with my laptop so I tried opening the same page on my phone but to no avail\
Checking the devtools reveals two typeErrors
![image](https://user-images.githubusercontent.com/94307595/201040483-51da865e-a463-4122-b6f9-bc45d8f555e6.png)

I don't know a lot about this stuff 😅

# Reproduction
Visit https://svelte.dev/repl

**Comment by iluvsoup** [comment]
Fixed itself? Sorry for wasting anyones time

**Comment by Conduitry** [comment]
https://github.com/sveltejs/svelte/issues/8010 This was a bug in Svelte 3.53.0 with the compiler not being able to run in the browser - it's been fixed in 3.53.1.
