### ISSUE TITLE
How to setup the `svelte.dev` locally to serve docs without `api.svelte.dev`?

### ISSUE THREAD

**Issue by nazarepiedady** [sveltejs/sites#423]
Salutes to you all, it may not seems a matter for an issue but
I really do not know where to go to get an answer, I am working 
on a community localisation to Portuguese of the entire svelte 
website and I am having trouble try to simplify the source code 
to serve the docs inside `svelte.dev/content` folder instead of 
having to fetch from `api.svelte.dev` backend, so I want to use 
the same approach used to serve the `svelte.dev/blog`.

**Comment by jakekwak** [comment]
can you tell me how to make it an api server(https://api.svlete.dev) using the local documentation(github.com/sveltejs/svelte/site/content) at https://github.com/sveltejs/api.svelte.dev

**Comment by nazarepiedady** [comment]
@jakekwak I referred myself to a way to the other documentation content
to be served as the `svelte.dev/content` is served, but I believe I will find a
solution or just have to setup the `api.svelte.dev`.

**Comment by benmccann** [comment]
We will be removing the API soon as we overhaul svelte.dev codebase to match the kit.svelte.dev codebase

**Comment by nazarepiedady** [comment]
@benmccann you give a good news, I will be waiting for it.

I am working on the localization of the documentation and its
entire website and to have the sources spread in such it is now
turn things a little too complex for me to maintain it.

**Comment by jakekwak** [comment]
@benmccann when is it available the no API version.  I already made [sveltekit](https://sveltekit.javapad.com/) and [learn](https://learn.javapad.com/).

**Comment by benmccann** [comment]
Here's the PR for it: https://github.com/sveltejs/svelte/pull/8432

**Comment by nazarepiedady** [comment]
@benmccann thank you so much. :relaxed:

**Comment by jakekwak** [comment]
@benmccann thank you...

**Comment by jakekwak** [comment]
@benmccann It works fine with local files. The only problem is that the `site/content/docs`  file has a directory structure. As a result, all links must be modified. (e.g. /docs#example to /docs/example).  Could you fix this?  or Could you merge this branch to https://github.com/sveltejs/sites ?

**Comment by benmccann** [comment]
I'm not sure which branch you're referring to. We'll setup redirects to the new directory structure though

**Comment by jakekwak** [comment]
@benmccann  [The original doc](https://github.com/sveltejs/svelte/tree/master/site/content/docs)

**Comment by jakekwak** [comment]
@benmccann  I think it is caused by the difference between [The original doc - file ](https://github.com/sveltejs/svelte/tree/master/site/content/docs) and [branch sites docs - directory structure](https://github.com/sveltejs/svelte/tree/sites/site/content/docs).

I want to use [the latest document file](https://github.com/sveltejs/svelte/tree/master/site/content/docs)
