### ISSUE TITLE
Provide a way to try Svelte on its own

### ISSUE THREAD

**Issue by alvinometric** [sveltejs/sites#425]
Hello, 
Since #410, there's no recommended quick start for just Svelte without Sveltekit. 

This is inconsistent with the tutorial and the docs on this website that are only about Svelte. It would be great to either

- Revert #410 and leave the old `create-vite` command since the Sveltekit website is self-contained.
- Make sure both commands are available

Thanks,
Alvin

**Comment by Conduitry** [comment]
I agree we want to steer most people towards SvelteKit. I think having the reference to the Vite template in the docs (but not on the Svelte homepage) is fine.
