### ISSUE TITLE
Svelte REPL, saved app deletion does not remove app div

### ISSUE THREAD

**Issue by andriytyurnikov** [sveltejs/sites#443]
### Describe the bug

Deletion of saved app does not remove app div

### Reproduction

Save an app, delete an app - app block is visible.

### Logs

```shell
[Violation] 'click' handler took 1995ms
```

### System Info

```shell
macOS 12.6.3 (21G419)

Google Chrome Version 110.0.5481.100 (Official Build) (x86_64)
```

### Severity

annoyance

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
