### ISSUE TITLE
Syntax highlighting is broken for else & elseif blocks

### ISSUE THREAD

**Issue by fkinsimple** [sveltejs/sites#448]
The syntax highlighting does not work correctly in `{:else}` & `{:else if}` blocks:
https://svelte.dev/repl/02b9c19b8c3f4b17bfcb9dd3efd28704?version=3.55.1

This example from the tutorial writes `5 > x` to get around the issue probably:
https://svelte.dev/tutorial/else-if-blocks

Might be similar to: #161

**Comment by gtm-nayan** [comment]
Can you send a screenshot? Everything looks normal to me.

**Comment by fkinsimple** [comment]
> Can you send a screenshot? Everything looks normal to me.

Yes, I don't recall much. It works now.
