### ISSUE TITLE
Add Apple to the "Who's using Svelte" section on svelte.dev

### ISSUE THREAD

**Issue by grandslammer** [sveltejs/sites#451]
Apple have rebuilt music.apple.com using Svelte and, according to Wappalyzer, is out of beta and is in production.

As a result, it would be good to see the Apple logo on the "Who's using Svelte" section of the homepage.

**Comment by Conduitry** [comment]
Yeah, we've been aware of this for a while, but we can't just put Apple's logo on their without an okay from the appropriate legal people there. My impression was that no one wanted to be the person to sign off on that, or even knew for sure who would be able to sign off on it. If someone who verifiably works at Apple opens a PR to add it, and they assert that they have gone through the proper channels to do so, that would probably suffice, but I don't think anything less than that would be.

**Comment by grandslammer** [comment]
That's a shame, it would have been great for the community. Hopefully it may happen in future. Thanks for the explanation.
