### ISSUE TITLE
Load more button on Who is using Svelte section is gone

### ISSUE THREAD

**Issue by opensas** [sveltejs/sites#46]
If I recall correctly there was a `load more` button on the **Who's using Svelte?** section of the site. The button is no longer to be found.

![image](https://user-images.githubusercontent.com/481687/122648600-5919cb80-d100-11eb-87d0-72186f6b1bde.png)

Also, this page is archived: https://github.com/sveltejs/community/blob/master/whos-using-svelte/WhosUsingSvelte.js

Don't know exactly whata that means.

**Comment by geoffrich** [comment]
See this PR: https://github.com/sveltejs/svelte/pull/6409

**Comment by benmccann** [comment]
Yes, we decided to remove that section. Only a small fraction of the logos were being displayed and it generated continuous requests to maintain it
