### ISSUE TITLE
Contrast issues on Examples page

### ISSUE THREAD

**Issue by RaphGL** [sveltejs/sites#493]
Hey, I was going through the Examples page today and noticed that the text wasn't showing up correctly on one of the examples so I went through the entire page looking for contrast issues. Here's what I found:

#### On dark mode
- Numbers are dark after typing on keyboard:
https://svelte.dev/examples/component-bindings

- Both the button and the text is white but their hover style is fine:
https://svelte.dev/examples/easing

- Text is too dark
https://svelte.dev/examples/area-chart

- The entire box is white and and illegible
https://svelte.dev/examples/slot-props

- Blue text is barely legible  
https://svelte.dev/examples/hacker-news

#### On light mode
- Text color is grey and barely legible
https://svelte.dev/examples/bar-chart

- The graph's lines aren't visible
https://svelte.dev/examples/scatterplot

- Grey text is too light
https://svelte.dev/examples/hacker-news

**Comment by dummdidumm** [comment]
hackernews, scatterplot and component-bindings should be better now.

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file an issue at https://github.com/sveltejs/svelte.dev if the issue persists
