### ISSUE TITLE
REPL breaks when deleting attributes

### ISSUE THREAD

**Issue by AdrianGonz97** [sveltejs/sites#496]
### Describe the bug

The REPL breaks while deleting whole words (<kbd>CTRL</kbd> + <kbd>Backspace</kbd>) on an element's attributes. 

I've been able to consistently get it to error when you start deleting from an attribute that's assigned to a string literal (.e.g., `value="press me"` in this case).

![gif example of the issue](https://i.imgur.com/LK8DKUE.gif)

### Reproduction

https://svelte.dev/repl/8abeb99dab034b93a4522a0ba80b1a19?version=4.0.0

### System Info

```shell
Issue occurs on Chrome
```

### Severity

annoyance

**Comment by PuruVJ** [comment]
This issue is fixed now. Can you confirm?

**Comment by AdrianGonz97** [comment]
Seems to be working perfectly! Thanks!! @PuruVJ
