### ISSUE TITLE
Todo app layout broken in animate tutorial

### ISSUE THREAD

**Issue by marvinhagemeister** [sveltejs/sites#498]
The layout of the todo app of the animate tutorial is broken for me in all major browsers.

Link: https://svelte.dev/tutorial/animate

<img width="1128" alt="Screenshot 2023-06-25 at 19 28 12" src="https://github.com/sveltejs/sites/assets/1062408/18276b2e-4fd5-4f49-9b75-4747de91eda1">

**Comment by benmccann** [comment]
looks okay to me now: https://svelte.dev/tutorial/svelte/animations
