### ISSUE TITLE
Allow loading a local folder when working on the repl

### ISSUE THREAD

**Issue by unlocomqx** [sveltejs/sites#538]
### Describe the problem

Editing in the repl can never match editing on your favorite editor/IDE

### Describe the proposed solution

Use the "File System Access API" to allow the user to load a local folder (I can provide a PR for this if you think it's a good idea)
This would allow the user to edit files locally and the changes will be synced to the repl and vice-versa

### Alternatives considered

I didn't find a workaround

### Importance

would make my life easier

**Comment by benmccann** [comment]
this sounds a bit too complicated for what the repl is supposed to be
