### ISSUE TITLE
Blog light mode style has red subtext

### ISSUE THREAD

**Issue by jasongitmail** [sveltejs/sites#539]
### Describe the bug

The blog's subhead styles in light mode appear as if they're error messages at first glance. I assume this is not intentional, given dark mode uses gray text for the subhead:

<img width="1036" alt="Screenshot 2023-09-27 at 10 03 56 PM" src="https://github.com/sveltejs/svelte/assets/50032291/66929834-ed18-4c24-9ab3-d56755cc3dc9">
<img width="1019" alt="Screenshot 2023-09-27 at 10 03 46 PM" src="https://github.com/sveltejs/svelte/assets/50032291/04194142-7cf3-4352-9185-0ce4d296db2c">

### Reproduction

Visit https://svelte.dev/blog in light mode.

### System Info

```shell
MacOS
```

### Severity

annoyance

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file an issue at https://github.com/sveltejs/svelte.dev if the issue persists
