### ISSUE TITLE
Svelte docs: ts-toggle button doesn't work

### ISSUE THREAD

**Issue by Jamoverjelly** [sveltejs/sites#541]
### Describe the bug

The button inside the `ts-toggle` div appearing at the base of the documentation's table of contents (last child of `toc-container`) doesn't switch the code examples from TypeScript to JavaScript

### Reproduction

n/a

### System Info

```shell
n/a
```

### Severity

annoyance

**Comment by benmccann** [comment]
closing since the site has been rewritten
