### ISSUE TITLE
Copy button in code blocks scrolls with overflowing content

### ISSUE THREAD

**Issue by stephenlrandall** [sveltejs/sites#542]
### Describe the bug

![IMG_7495](https://github.com/sveltejs/svelte/assets/41397226/55538bf8-71e5-4d80-9d57-e5d4ca2a3cf4)

from the Svelte 5 FAQ.

### Reproduction

https://svelte-5-preview.vercel.app/docs/faq

### System Info

```shell
iOS 17, Safari
```

### Severity

annoyance

**Comment by benmccann** [comment]
closing since the site has been rewritten
