### ISSUE TITLE
[Bug] Svelte.dev "Who's using Svelte" not displaying correctly on Safari 15.0

### ISSUE THREAD

**Issue by AdrienMergalet** [sveltejs/sites#55]
Who's using Svelte part of the website is not displaying correctly on safari

![image](https://user-images.githubusercontent.com/22292245/135264896-3aed0ef3-73ba-4d9a-a1e6-be1e0d23beea.png)

Works fine on Chrome and Firefox

**Comment by benmccann** [comment]
This has been re-implemented. I don't have Safari to test, so will assume it's fixed. Let me know if it still happens
