### ISSUE TITLE
Grant read access for TOR users and other entities deemed non-human by Cloudflare

### ISSUE THREAD

**Issue by mk-pmb** [sveltejs/sites#559]
Hi! I use TOR by default, which in Cloudflare's terms makes me a non-human. I agree that it can be troublesome to accept write access from TOR users. However, could you be so kind and grant me _read_ access to https://svelte.io/ (and potentially related sites) even anonymously?

Edit: I see now that https://svelte.io/ is different from https://svelte.dev/ . The latter currently seems to work.

**Comment by Conduitry** [comment]
svelte.io isn't actually under our control. I'm not sure who owns that. I believe it just proxies requests behind the scenes to svelte.dev - which also means that logging into the REPL with GitHub doesn't work, But in any case, that is effectively someone else's site and shouldn't be trusted as an official resource.

**Comment by mk-pmb** [comment]
Thanks for clarifying! :+1:
