### ISSUE TITLE
Broken link for runes on the Svelte Hack prizes page

### ISSUE THREAD

**Issue by Gjeev** [sveltejs/sites#562]
On this [page](https://hack.sveltesociety.dev/2024/prizes), when i clicked on the runes link, it led me to a 404 page. 
![image](https://github.com/user-attachments/assets/1b20b9c5-2409-4e34-bf86-04e44ff3a12d)

**Comment by Conduitry** [comment]
Please report this issue on https://github.com/svelte-society/svelte-hack - The Svelte Society sites don't live here and aren't run by the Svelte maintainers.

**Comment by benmccann** [comment]
https://github.com/svelte-society/svelte-hack/pull/3

**Comment by ghostdevv** [comment]
Ty for reporting this @Gjeev and ty for the pr @benmccann - the fix should be live now! :pray:
