### ISSUE TITLE
syntax highlighting for inline styles

### ISSUE THREAD

**Issue by Rich-Harris** [sveltejs/sites#79]
far from a priority, but i thought [this](https://twitter.com/atomiksdev/status/1467097220113526786) was pretty cool

![image](https://user-images.githubusercontent.com/1162160/144748747-e388ce1f-446c-4d2c-aafa-15ec1453e269.png)

**Comment by pngwn** [comment]
I think this would happen here: https://github.com/sveltejs/action-deploy-docs

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
