### ISSUE TITLE
Syntax highlighting on blog posts appears to be broken.

### ISSUE THREAD

**Issue by Tropix126** [sveltejs/sites#80]
Seems that the new site isn't loading the codeblock theme styles on the blog. The classes themselves are applied properly, just not the CSS.

![image](https://user-images.githubusercontent.com/42101043/146092736-227b40ee-6256-4645-a054-9d27da8675a2.png)

**Comment by Tropix126** [comment]
![image](https://user-images.githubusercontent.com/42101043/146095200-e58a0ab3-9f5a-4fb5-8ec4-4a4545892e4b.png)

Also appears to affect the FAQ.

**Comment by Rich-Harris** [comment]
Thanks — fixed the blog styles, the FAQ styles is a preexisting issue. Though to be honest that whole page is probably due for an update, and should probably be folded into the docs
