### ISSUE TITLE
kit.svelte.dev - Broken navbar and hero.

### ISSUE THREAD

**Issue by Tropix126** [sveltejs/sites#81]
Seems like the new site changes have broken some aspects of the SvelteKit site. Notably, icons in the navbar are [404ing](https://kit.svelte.dev/icons/discord.svg) and blurbs are now separated from the hero causing some extra space.
![image](https://user-images.githubusercontent.com/42101043/146093058-3604d666-349b-4a89-b1eb-692cca9d05ea.png)

**Comment by benmccann** [comment]
Fixed
