### ISSUE TITLE
svelte.dev docs incorrect page title

### ISSUE THREAD

**Issue by adamjkb** [sveltejs/sites#85]
https://svelte.dev/docs page title is "Docs • SvelteKit" instead of "Docs • Svelte"

https://github.com/sveltejs/sites/blob/d03e62bda6b7c7497aa6c08f9e5adb8ccbdcb49c/sites/svelte.dev/src/routes/docs/index.svelte#L35

**Comment by benmccann** [comment]
thanks. there were a few others too

fixed here: https://github.com/sveltejs/sites/commit/f3d6149ee5a9c65936a7e74a21a80b003ddf322f
