### ISSUE TITLE
SvelteKit Website Github link url is Svelte's repo

### ISSUE THREAD

**Issue by f-elix** [sveltejs/sites#87]
### Describe the bug

The Github link in the website's header links to Svelte's repo instead of Sveltekit's.

### Reproduction

Go to Sveltekit's website and click the Github link.

### System Info

```shell
Not needed
```

### Severity

annoyance

**Comment by benmccann** [comment]
fixed https://github.com/sveltejs/sites/commit/41e52abdfa5f73abf7aac6b29852b7d519b79554
