### ISSUE TITLE
sites/svelte.dev/README.md needs updating

### ISSUE THREAD

**Issue by Conduitry** [sveltejs/sites#88]
`sites/svelte.dev/README.md` looks like it was mostly/entirely copied over from the version in the main Svelte repo, and it doesn't reflect the current state of reality, or actually tell people how to run the site locally or use a local copy of the Svelte compiler in the REPL.

**Comment by Conduitry** [comment]
We may also need to add a local API server to the Svelte repo? I'm not sure how we want this to be set up.

**Comment by Conduitry** [comment]
The first few things are now handled, but I'm still going to leave this open pending some sort of documented setup with a local API server for the documentation sites.

**Comment by benmccann** [comment]
closing since we no longer have an API server. I have a PR pending over at the new site to add a contributing guide that I could use some help with
