### ISSUE TITLE
[site] Add a share button in the REPL page controls

### ISSUE THREAD

**Issue by johannchopin** [sveltejs/sites#95]
### Describe the problem

REPL is an awesome tool to help people learn Svelte. A good example for that is StackOverflow where I add a REPL to almost all my `svelte` related answers/questions. The problem is that there is no 'common' way to share the REPL link other than the link itself so you will see in many answers stuff like:

> Have a look at the [REPL](/repl-link)
> Here is an example: https://svelte.dev/repl/hello-world?version=3.42.2
> ...

It is therefore more or less difficult to find the final example quickly in the text where other platforms such as codesandbox  provides a button that is markdown/html that you can easily copy/paste like:

```md
[![Edit cranky-boyd-3qqnq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-boyd-3qqnq?fontsize=14&hidenavigation=1&theme=dark)
```

[![Edit cranky-boyd-3qqnq](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/cranky-boyd-3qqnq?fontsize=14&hidenavigation=1&theme=dark)

### Describe the proposed solution

Would be nice in the [REPL's AppControls](https://github.com/sveltejs/svelte/blob/master/site/src/routes/repl/%5Bid%5D/_components/AppControls/index.svelte) to add a `share` button that will open a panel that proposes you to copy the REPL link or the markdown/html button code like:

![image](https://user-images.githubusercontent.com/31794680/130351617-4dc18989-1ce0-4c2b-9403-0596adbba298.png)

TODOS:

- create button svg
- host static svg on the svelte site
- add control button to open panel that includes:
  - a button to copy the URL
  - 2 textareas that contains the html/markdown of the button and a preview of it

This isn't a lot of work and I would be glad to help the svelte ecosystem that I enjoy so much. I can take care of this one if everyone agree 😄 

### Alternatives considered

n/a

### Importance

would make my life easier

**Comment by benmccann** [comment]
closing since the corresponding PR was closed. we have a couple of issues for embeds already
