### ISSUE TITLE
Adding a switch for change themes

### ISSUE THREAD

**Issue by Ritwik880** [sveltejs/sites#97]
**Is your feature request related to a problem? Please describe.**
Dark Mode is a supplemental mode that can be used to display mostly dark surfaces on the UI. The design reduces the light emitted by device screens while maintaining the minimum color contrast ratios required for readability.
Additionally, it conserves battery power.

**Comment by lukaszpolowczyk** [comment]
Definitely in the first place, docs should support css `prefers-color-scheme`.
That is, as it is in Mozilla Docs - a button consisting of three options:
![obraz](https://user-images.githubusercontent.com/16800535/187187491-4cf0e40a-cff1-4354-b382-3e8e4affd8f1.png)

**Comment by benmccann** [comment]
closing since the site has been rewritten. please file at https://github.com/sveltejs/svelte.dev/issues/new if the issue persists
